### ISSUE TITLE
Warnnings

### ISSUE THREAD

**Issue by marcelog09** [maddinat0r/samp-mysql-yinline-include#10]
I get the following warnings when using it:

\pawno\include\a_mysql_yinline.inc(61) : warning 234: function is deprecated (symbol "Callback_Get") Remove or use `Indirect_Claim(func);`.
\pawno\include\a_mysql_yinline.inc(250) : warning 234: function is deprecated (symbol "Callback_Get") Remove or use `Indirect_Claim(func);`.
\pawno\include\a_mysql_yinline.inc(666) : warning 234: function is deprecated (symbol "Callback_Release") Remove or use `Indirect_Release(func);`.

Does it interfere with something?

**Comment by maddinat0r** [comment]
You might get these errors depending on what YSI version you're using. This helper include is supposed to work with YSI 3 (and 4 I think), you're probably using YSI 5. You can probably ignore those warnings, or provide a pull request with the required changes to make them go away.
