### ISSUE TITLE
Incompatible with JIT plugin

### ISSUE THREAD

**Issue by zsoolt997** [maddinat0r/samp-mysql-yinline-include#13]
`#include <a_mysql_yinline>`

Included in my script.

`plugins jit sscanf chrono pawnregex pawncmd mysql streamer`

JIT plugin in server.cfg. When I start my server, simply closes itself without any warning, or log. It gives me some warning too when I compile my code, releated to the new y_inline.

**Comment by maddinat0r** [comment]
If you're using YSI 5.x, you should use the built-in y_inline MySQL functions shipped with YSI. This include will only properly work on YSI 4 and 3.
I'm not sure though if YSI 5 supports JIT, but I'd likely expect there being support for it in version 5 rather than 4 or 3.

**Comment by zsoolt997** [comment]
Yeah I'm using YSI 5.x and already found the inline functions to MySQL.
It is supporting, at least I have no problem with them. Also the YSI detect's whether you are using JIT or no.

![Jegyzet 2020-04-03 003127](https://user-images.githubusercontent.com/22081818/78305984-95d0c580-7542-11ea-938e-8eb970cd1398.png)

Thanks for the reply, I will close this thread.
