### ISSUE TITLE
Bug a_mysql_yinline.inc

### ISSUE THREAD

**Issue by Lathrel** [maddinat0r/samp-mysql-yinline-include#5]
When I call ```mysql_tquery_inline``` and restart server, when server reconect I get this error.

```
[15:13:32] [debug] Run time error 5: "Invalid memory access"
[15:13:32] [debug] AMX backtrace:
[15:13:32] [debug] #0 0004687c in ?? (291848) from main.amx
[15:13:32] [debug] #1 0002db98 in public __MysqlInlineProcessCallback (291868, 291848, 5) from main.amx
```

This error only happens with the ```mysql_tquery_inline``` and ```mysql_pquery_inline```

**Comment by marlonlorran** [comment]
UP

**Comment by Lathrel** [comment]
@maddinat0r

**Comment by maddinat0r** [comment]
Sorry, totally forgot about this. I'll try to reproduce your bug this weekend.
Do you use Zeex' compiler or the default one? Which YSI version are you using?
Also linking the YSI issue here you created: Misiur/YSI-Includes#223

**Comment by Lathrel** [comment]
I'm using Zeex' compiler and YSI 4.0.1

**Comment by Lathrel** [comment]
@maddinat0r Can close this issue.
Already fixed on https://github.com/Misiur/YSI-Includes/issues/223

Thanks.

**Comment by maddinat0r** [comment]
Alright, great! Thanks to @misiur and @Y-Less!
